spinnaker:
  cassandra:
    enabled: false
    cluster: 'spinnaker'
    keyspace: 'echo'
  baseUrl: 'http://localhost:9000'

kafkaConsumer:
  enabled: true
  pollingIntervalMs: 30000
  brokers:
    - name: kafka
      address: 'http://localhost:3434'

echo:
  baseUrl: 'http://localhost:8080'

front50:
  baseUrl: 'http://localhost:8081'

orca:
  baseUrl: 'http://localhost:8083'

search:
  index: 'event_history'
